version: "3"
services:
  pelican-sitebuilder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/project-root
    command: pelican -l content -s pelicanconf.py -r --bind 0.0.0.0
